name: Arena
main: kabal.arena.plugin.Arena
version: "0.1"
commands:
    arStart:
        description: Starts the event.
        usage: /<command> 
    arStop:
        description: Stops the event
        usage: /<command> 
    arAddRed:
        description: Adds player to team RED
        usage: /<command> 
    arAddBlue:
        description: Adds player to team BLUE
        usage: /<command> 
    arRoundLimit:
        description: Sets round limit
        usage: /<command> 
    arRemovePlayer:
        description: Remove Player
        usage: /<command>
    arSpec:
        description: Set the spectator spawn point
        usage: /<command>